### ISSUE TITLE
Removes query parameters from the URL

### ISSUE THREAD

**Issue by luontola** [lambdaisland/fetch#10]
If I do a request using JavaScript fetch, `(js/fetch "/example?foo=bar")`, it does a `GET /example?foo=bar` request.

But if I do the same request using lambdaisland fetch, `(lambdaisland.fetch/get "/example?foo=bar")`, it does a `GET /example` request.

It should not drop the query parameters from the URL.

**Comment by plexus** [comment]
Note that this works:

```clojure
(fetch/get "/example" {:query-params {:foo "bar"}})
```

although I agree it wouldn't be bad to merge in params that are in the URL already. PR welcome, we're already using [lambdaisland/uri](https://github.com/lambdaisland/uri) on this so this should be straightforward.
