### ISSUE TITLE
Usage in Node?

### ISSUE THREAD

**Issue by aviflat** [lambdaisland/fetch#17]
Hi, I’m a longtime JVM Clojurist who’s just now getting started with ClojureScript on Node.

I just started looking for a good CLJS-compatible HTTP client library, and so far it looks like maybe people are just using JS Node libs, like Axios or node-fetch? I’m not sure.

Anyway, while I was researching this, I stumbled across this library. The README doesn’t mention Node, which made me curious whether Node supports the Fetch API. So I looked into that, and found that in fact Node _just_ [added such support on 2022-02-10](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md#2022-02-10-version-1750-current-ruyadorno) as an experimental (behind a flag) feature. (I’m not super familiar with the Node community, but I’d guess this API is likely to become standardized (non-experimental) within a few months or a year or so?)

Anyway, since Node now more or less has Fetch, any chance this library will add support for running on Node? Or, actually, it just occurred to me — maybe it’ll Just Work? Either way, it’d be great to see this addressed in the docs — even if only to say, if necessary “this won’t work on Node, don’t bother”.

Thanks!

**Comment by plexus** [comment]
If they have a compliant implementation available as `js/fetch` then I see no reason why it wouldn't work. Maybe try it out? If there any specific caveats that apply to Node then those can go into the README.

**Comment by aviflat** [comment]
OK, will do. Thanks!

**Comment by aviflat** [comment]
I started changing my project code to use this lib, but then I realized that it’s not really necessary in that particular project.

So instead I did a little manual testing:

```clojure
cljs.user=> (require '[lambdaisland.fetch :as fetch])
nil
cljs.user=> (fetch/get "https://httpbin.org/uuid")
#object[Promise [object Promise]]
cljs.user=> (def r *1)
#'cljs.user/r
cljs.user=> (-> r (.then :body) (.then println))    
{:status 200, :headers {access-control-allow-credentials true, access-control-allow-origin *, connection keep-alive, content-length 53, content-type application/json, date Thu, 24 Feb 2022 14:37:50 GMT, server gunicorn/19.9.0}, :body #js {:uuid a5cacf24-d7d0-4a0b-b976-a7ddcf4909e7}}
#object[Promise [object Promise]]
```

(If the above looks awkward it’s at least partly because I’m inexperienced working with promises, and inexperienced with ClojureScript specifically, as opposed to JVM Clojure.)

Anyway, this looks pretty good to me.

If it’s OK, I have some ideas on a few tweaks to the README to inform users that this is possible, with a few tips; maybe also an automated test to prevent regressions on Node. Open to a PR or two?

**Comment by plexus** [comment]
Sure!

**Comment by plexus** [comment]
For anyone looking for this, you can use it on node using the `node-fetch` package version `2.6.1`, using this snippet

https://github.com/lambdaisland/fetch/blob/main/test/lambdaisland/fetch_test.cljs#L11-L12

Later versions are packaged differently and don't work.
